name: ai_productivity_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0' # Updated to support null safety

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png

fonts:
  - family: Latha
    fonts:
      - asset: assets/fonts/Latha.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
